using AdventOfCode_2024;
//Console.WriteLine($"The solution of the Historian Hysteria problem is {HistorianHysteria.GetInput()}");
//Console.WriteLine($"The solution of the Red Nosed Reports problem is {RedNosedReports.GetInput()}");
//Console.WriteLine($"The solution of the Mull it Over problem is {MullItOver.GetInput()}");
//Console.WriteLine($"The solution of the Ceres Search problem is {CeresSearch.GetInput()}");
//Console.WriteLine($"The solution of the Print Queue problem is {PrintQueue.GetInput()}");
//Console.WriteLine($"The solution of the Guard Gallivant problem is {GuardGallivant.GetInput()}");
//Console.WriteLine($"The solution of the Bridge Repair problem is {BridgeRepair.GetInput()}");
//Console.WriteLine($"The solution of the Resonant Collinearity problem is {ResonantCollinearity.GetInput()}");
//Console.WriteLine($"The solution of the Disk Fragmenter problem is {DiskFragmenter.GetInput()}");
//Console.WriteLine($"The solution of the HoofIt problem is {HoofIt.GetInput()}");
//Console.WriteLine($"The solution of the Plutonian Pebbles problem is {PlutonianPebbles.GetInput()}");
//Console.WriteLine($"The solution of the Garden Groups problem is {GardenGroups.GetInput()}");
//Console.WriteLine($"The solution of the Claw Contraption problem is {ClawContraption.GetInput()}");
//Console.WriteLine($"The solution of the Restroom Redoubt problem is {RestroomRedoubt.GetInput()}");
//Console.WriteLine($"The solution of the Warehouse Woes problem is {WarehouseWoes.GetInput()}");
//Console.WriteLine($"The solution of the Reindeer Maze problem is {ReindeerMaze.GetInput()}");
//Console.WriteLine($"The solution of the Chronospatial Computer problem is {ChronospatialComputer.GetInput()}");
//Console.WriteLine($"The solution of the Ram Run problem is {RamRun.GetInput()}");
//Console.WriteLine($"The solution of the Linnen Layout problem is {LinnenLayout.GetInput()}");
//Console.WriteLine($"The solution of the Race Condition problem is {RaceCondition.GetInput()}");
//Console.WriteLine($"The solution of the Keypad Conundrum problem is {KeypadConundrum.GetInput()}");
//Console.WriteLine($"The solution of the Money Market problem is {MoneyMarket.GetInput()}");
//Console.WriteLine($"The solution of the LAN Party problem is {LANParty.GetInput()}");
//Console.WriteLine($"The solution of the Crossed Wires problem is {CrossedWires.GetInput()}");
Console.WriteLine($"The solution of the Code Chronicle problem is {CodeChronicle.GetInput()}");
